### ISSUE TITLE
php版本为7时 会因为版本判断逻辑 导致收集数据失败

### ISSUE THREAD

**Issue by JREAMLU** [dreamans/phpAnalysis#3]
https://github.com/dreamans/phpAnalysis/blob/af96619c8c7a663c6274819473e22b97e4ffb7bb/agent/header.php#L25
建议改成 
```
if(version_compare(PHP_VERSION,'5.3.0','le')){  
    echo '小于5.3.0 ';
}
```

**Comment by zhangya4548** [comment]
我也遇到一样问题,这句就算注释了,也收集不到任何数据

**Comment by JREAMLU** [comment]
error_log里有输出什么嘛

**Comment by JREAMLU** [comment]
@zhangya4548 error_log里有输出什么嘛

**Comment by zhangya4548** [comment]
@JREAMLU 
require_once(/home/www/phpAnalysis/agent/../nimble/src/Nimble/nimble.php): failed to open stream: No such file or directory

**Comment by JREAMLU** [comment]
#4

**Comment by JREAMLU** [comment]
@zhangya4548 #4 这里回了

**Comment by dreamans** [comment]
已经修复，感谢反馈！
