### ISSUE TITLE
你好,非常感谢这个项目

### ISSUE THREAD

**Issue by xuyangbao3** [dreamans/phpAnalysis#8]

**Comment by xuyangbao3** [comment]
有个问题,我安装好以后数据库里一直没有数据,也就是首页列表一直处于空的状态,.想知道原因,ps安装的扩展名字是tideways_xhprof,在header.php文件验证完扩展是否load以后将名字改回来您最初的命名.

**Comment by xuyangbao3** [comment]
``  3 $extName = 'tideways_xhprof';
  4 
  5 // 检测扩展是否存在
  6 if (!extension_loaded($extName)) {
  7     error_log('phpAnalysis - php extension '. $extName .'must be loaded');
  8     return;
  9 }
 10 
 11 $extName = 'tideways';

**Comment by xuyangbao3** [comment]
`  3 $extName = 'tideways_xhprof';
  4 
  5 // 检测扩展是否存在
  6 if (!extension_loaded($extName)) {
  7     error_log('phpAnalysis - php extension '. $extName .'must be loaded');
  8     return;
  9 }
 10 
 11 $extName = 'tideways';`

**Comment by dreamans** [comment]
可安装https://github.com/tideways/php-xhprof-extension  4.*版本扩展

**Comment by xuyangbao3** [comment]
如何能比较方便的联系到你?qq434433135麻烦加一下好吗?

**Comment by xuyangbao3** [comment]
tideways | 4.1.5
-- | --
Connection (tideways.connection) | unix:///var/run/tideways/tidewaysd.sock
UDP Connection (tideways.udp_connection) | 127.0.0.1:8135

**Comment by xuyangbao3** [comment]
按照您说的我现在换成tideways4.1.5,中间遇到重复加载的问题也解决了,但是还是没有数据,而当我运行php header.php文件的时候回产生是数据,这个header.php是咱们项目agent下面的,我正常用网络访问服务器还是没有数据.ps 在php.ini第一行已经用绝对路径引入了咱们这个文件

**Comment by xuyangbao3** [comment]
后面又重新试了下,改为在php.ini文件最后一行引入,重启Nginx和php-fpm后可以了,谢谢,想加入这个项目做点贡献

**Comment by xuyangbao3** [comment]
记录了安装里程
https://github.com/xuyangbao3/install_phpAnalysis/issues
谢谢楼主,也希望其他有一样问题的人能顺利解决

**Comment by jiankeluoluo** [comment]
额，项目好像还是个半成品？没有Nimble这块的控制器？那你把表字段做上注释也行啊，界面接口就自己先写写也行
